name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.19
homepage: https://github.com/lejard-h/google_maps_webservice

environment:
  sdk: ">=1.20.1 <3.0.0"

dependencies:
  http: ">=0.13.0 <1.0.0"
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.5
  pedantic: ^1.11.0
  coverage: ^0.14.1
  test_coverage: ^0.5.0